[project]
name = "k8s-configs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.5",
    "jinja2-base64-filters>=0.1.4",
    "kubernetes>=32.0.0",
]
